Repository Easya-Solutions/dolibarr, pull requests merged in 2023-04, with the labels that each got.

#365 Some fix
  htdocs/accountancy/class/lettering.class.php
  htdocs/bookmarks/bookmarks.lib.php
  htdocs/fourn/facture/card.php
Labels: Already merged

#368 fix easya only since it is a problem that is not present in dolibarr/develop
  htdocs/ticket/card.php
Labels: easya only

#370 CORE variants: Fix update ref variant product on the combination page of the parent product PR #24465
  htdocs/variants/combinations.php
Labels: check merged

#355 NEW accountancy export API
  htdocs/accountancy/class/accountancyexport.class.php
  htdocs/accountancy/class/api_accountancy.class.php
  htdocs/accountancy/tpl/export_journal.tpl.php
  htdocs/core/lib/accounting.lib.php
  htdocs/core/lib/functions2.lib.php
  htdocs/core/modules/modAccounting.class.php
Labels: easya only, check merged

#379 2022.5.3 Manage payments for contracts
  htdocs/compta/facture/class/facture.class.php
  htdocs/public/payment/paymentok.php
Labels: Already merged

#380 2022.5.3 payment use browser language
  htdocs/public/payment/newpayment.php
  htdocs/public/payment/paymentko.php
  htdocs/public/payment/paymentok.php
Labels: Already merged

#382 FIX API accountancy export with download file
  htdocs/accountancy/class/api_accountancy.class.php
Labels: easya only, Todo
