Repository Easya-Solutions/dolibarr, pull requests merged in 2023-10, with the labels that each got.

#536 NEW VAT rates support multientities
  htdocs/accountancy/admin/index.php
  htdocs/admin/dict.php
  htdocs/admin/limits.php
  htdocs/core/class/html.form.class.php
  htdocs/core/lib/functions.lib.php
  htdocs/core/lib/price.lib.php
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
  htdocs/install/mysql/tables/llx_c_tva.key.sql
  htdocs/install/mysql/tables/llx_c_tva.sql
  htdocs/product/card.php
  htdocs/product/price.php
  htdocs/societe/class/societe.class.php
  htdocs/societe/price.php
Labels: easya 2024

#520 FIX group by in count elements on invoice list
  htdocs/compta/facture/list.php
  htdocs/modulebuilder/template/myobject_list.php
Labels: easya only

#504 NEW inventory without virtual products (kits)
  htdocs/product/inventory/class/inventory.class.php
Labels: Already merged, easya 2024

#503 NEW propagate demand reason in invoice card (PR #20538)
  htdocs/commande/list.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/list.php
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
  htdocs/install/mysql/tables/llx_facture.sql
Labels: easya only

#502 FIX remove special product lines on discount create (PR #21068)
  htdocs/compta/paiement/class/paiement.class.php
Labels: easya only

#543 CORE bankaccount: Add trigger when delete a bank account line PR #26092
  htdocs/compta/bank/class/account.class.php
Labels: Report Easya 2024

#483 Ajustement affichage Date, montant fr_GA
  htdocs/langs/fr_GA/main.lang
Labels: easya only

#434 Add new substitutions
  htdocs/core/lib/functions.lib.php
Labels: easya only, Report Easya 2024

#552 FIX Accountancy - FEC/FEC2 format with source file - Recover also supplier invoice in archive
  htdocs/accountancy/class/accountancyexport.class.php
Labels: Report Easya 2024

#558 Add hook printFieldListFrom on project list
  htdocs/projet/list.php
Labels: Already merged

#563 PHP 8.2 - Fix Accountancy 2 Warnings
  htdocs/accountancy/admin/account.php
Labels: to repost, easya 2024

#564 Add hook printFieldListSearchParam on project list
  htdocs/projet/list.php
Labels: Already merged, easya 2024

#565 fix duplicate ticket information
  htdocs/ticket/card.php
Labels: Already merged, easya 2024

#566 Use browser language for payment pages
  htdocs/public/payment/newpayment.php
  htdocs/public/payment/paymentko.php
  htdocs/public/payment/paymentok.php
Labels: Already merged, easya 2024

#567 2022.5.3 rc stockable product
  htdocs/core/lib/product.lib.php
  htdocs/expedition/card.php
  htdocs/expedition/class/expedition.class.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_product.sql
  htdocs/langs/en_US/products.lang
  htdocs/langs/fr_FR/products.lang
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/product/list.php
  htdocs/product/stock/class/mouvementstock.class.php
Labels: check merged, Report Easya 2024

#571 CORE mrp: NEW Option pour annuler les lignes de consommation et de production à l'annulation ou suppression d'un ordre de fabrication PR #26254
  htdocs/langs/en_US/mrp.lang
  htdocs/langs/fr_FR/mrp.lang
  htdocs/mrp/class/mo.class.php
  htdocs/mrp/mo_card.php
  htdocs/mrp/mo_production.php
Labels: easya 2024

#572 Set max length of product fourn ref to 255. For a client.
  htdocs/product/fournisseurs.php
Labels: easya only, Report Easya 2024

#568 2024.0.0 rc new stockableproduct
  htdocs/core/lib/product.lib.php
  htdocs/expedition/card.php
  htdocs/expedition/class/expedition.class.php
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
  htdocs/install/mysql/tables/llx_product.sql
  htdocs/langs/en_US/products.lang
  htdocs/langs/fr_FR/products.lang
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/product/list.php
  htdocs/product/stock/class/mouvementstock.class.php
Labels: check merged, easya 2024

#580 2024.0.0 version
  htdocs/accountancy/admin/account.php
  htdocs/main.inc.php
  htdocs/projet/list.php
  htdocs/ticket/card.php
Labels: easya only

#581 Backport getElementProperties from V18 to avoid fatal error
  htdocs/core/lib/functions.lib.php
Labels: Already merged
