Repository Easya-Solutions/dolibarr, pull requests merged in 2023-05, with the labels that each got.

#386 FIX edit field value of url
  htdocs/core/class/html.form.class.php
Labels: Already merged

#396 end accounting period
  htdocs/accountancy/tpl/export_journal.tpl.php
Labels: check merged

#397 Fix of a missing $conf
  htdocs/core/class/html.formaccounting.class.php
Labels: check merged

#399 Lot of corrections
  htdocs/accountancy/admin/index.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_societe_perentity.sql
  htdocs/langs/fr_FR/accountancy.lang
  htdocs/societe/card.php
  htdocs/societe/class/societe.class.php
Labels: easya only

#407 FIX Accountancy - Retained Warranty - calculation problem
  htdocs/accountancy/journal/sellsjournal.php
Labels: easya only
