Repository Easya-Solutions/dolibarr, pull requests merged in 2023-01, with the labels that each got.

#162 NEW make sell or eat by mandatory in product lot (PR #21710)
  htdocs/core/class/html.form.class.php
  htdocs/fourn/commande/dispatch.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_product.sql
  htdocs/langs/en_US/productbatch.lang
  htdocs/langs/fr_FR/productbatch.lang
  htdocs/product/ajax/product_lot.php
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/product/stock/class/productlot.class.php
  htdocs/product/stock/productlot_card.php
  htdocs/product/stock/tpl/stockcorrection.tpl.php
  htdocs/reception/class/reception.class.php
Labels: check merged

#225 NEW operation type in email collector to load or create contact
  htdocs/admin/emailcollector_card.php
  htdocs/emailcollector/class/emailcollector.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
Labels: postponed-dlb

#206 FIX: Reload page on supplier change and keeping the values PR #22756
  htdocs/fourn/commande/card.php
  htdocs/fourn/facture/card.php
Labels: postponed-dlb

#267 CORE Fix: Rights on action for payments by bank transfer PR #23687
  htdocs/compta/prelevement/card.php
Labels: easya only, check merged

#222 NEW filter on entity in import
  htdocs/core/modules/import/import_csv.modules.php
  htdocs/core/modules/import/import_xlsx.modules.php
  htdocs/core/modules/import/modules_import.php
Labels: check merged

#268 2022.5.3 rc ticket message support custom substitution function
  htdocs/core/class/html.formticket.class.php
  htdocs/ticket/card.php
Labels: easya only
