Repository Easya-Solutions/dolibarr, pull requests merged in 2023-02, with the labels that each got.

#271 NEW Order export : allow to export field 'shipment method'.
  htdocs/core/modules/modCommande.class.php
Labels: check merged

#272 Fix for Open-DSI only, fix on ticket mail_intro and mail_signature
  htdocs/core/class/html.formticket.class.php
Labels: easya only

#283 2022.5.3 fix supplier reload page
  htdocs/fourn/commande/card.php
Labels: check merged

#280 FIX attached files and send by mail using trackid from ticket form
  htdocs/core/class/html.formticket.class.php
  htdocs/ticket/card.php
Labels: check merged

#293 Update llx_accounting_account_fr.sql
  htdocs/install/mysql/data/llx_accounting_account_fr.sql
Labels: Already merged
