Repository Easya-Solutions/dolibarr, pull requests merged in 2023-11, with the labels that each got.

#590 Fix running SQL files with multilines requests
  htdocs/core/lib/admin.lib.php
Labels: Already merged

#591 FIX Accountancy - display of the ledger
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/class/accountingjournal.class.php
Labels: Already merged, easya 2024

#592 FIX Accountancy - display of the ledger
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/class/accountingjournal.class.php
Labels: Already merged

#599 NEW order by batch number in product batch find all method
  htdocs/product/class/productbatch.class.php
Labels: easya 2024

#614 CORE document: Fix get shared document when the element is shared between multiple entities
  htdocs/document.php
Labels: easya only, easya 2024

#615 CORE html form: NEW: Add global PRODUCT_DONOTSHOW_PRODUCTWITHNOSUPPLIERPRICE
  htdocs/core/class/html.form.class.php
Labels: check merged, easya 2024

#618 CORE expedition: Ajout de la fonction get_substitutionarray_other() dans le modele ODT des expédition
  htdocs/core/modules/expedition/doc/doc_generic_shipment_odt.modules.php
Labels: easya 2024

#616 Reception dispatch : copy previous entrepot
  htdocs/fourn/js/lib_dispatch.js.php
Labels: Report Easya 2024

#617 CORE propal: Add missing code for THIRDPARTY_PROPAGATE_EXTRAFIELDS_TO_PROPAL on propal card
  htdocs/comm/propal/card.php
Labels: easya only, check merged, easya 2024

#620 NEW mrp: Add context for the movement stock (role toconsume/toproduce) on mrp
  htdocs/mrp/mo_production.php
Labels: easya 2024

#622 NEW Supplier order - Introduce constant ORDER_SUPPLIER_METHOD_BY_DEFAULT to define order method by default #20557
  htdocs/fourn/commande/card.php
Labels: easya only

#624 fix user off constants not saved
  htdocs/admin/agenda.php
  htdocs/admin/ecm.php
  htdocs/core/ajax/constantonoff.php
Labels: easya only

#627 FIX Export FEC/FEC2 - Clean some characters
  htdocs/accountancy/class/accountancyexport.class.php
Labels: easya 2024

#628 NEW Accountancy - Add partial lettering
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/class/lettering.class.php
  htdocs/langs/en_US/accountancy.lang
  htdocs/langs/fr_FR/accountancy.lang
  htdocs/langs/fr_GA/accountancy.lang
Labels: easya only

#629 NEW Accountancy - Add partial lettering
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/class/lettering.class.php
  htdocs/langs/en_US/accountancy.lang
  htdocs/langs/fr_FR/accountancy.lang
Labels: easya only, easya 2024

#637 FIX #26536 Accountancy - Balance - Not divided lines by label & account, only by account
  htdocs/accountancy/bookkeeping/balance.php
  htdocs/accountancy/class/bookkeeping.class.php
Labels: Already merged

#638 FIX #25967 Supplier export - Missing filter on accountancy buy account
  htdocs/core/modules/modFournisseur.class.php
Labels: Already merged

#640 CORE prelevement : Correction du test pour verifier si ICS est renseigner sur la banque lors de la creation d'un bon de prelevement
  htdocs/compta/prelevement/create.php
Labels: to repost
