Repository Easya-Solutions/dolibarr, pull requests merged in 2023-03, with the labels that each got.

#319 NEW adapt category and product pictures sizes on takepos
  htdocs/takepos/css/pos.css.php
  htdocs/takepos/index.php
Labels: check merged

#327 Bugfix inside selectTypesTickets function inside html.formticket.class.php
  htdocs/core/class/html.formticket.class.php
Labels: check merged

#341 add a hidden const to show the EF inside a public ticket view
  htdocs/core/tpl/extrafields_view.tpl.php
Labels: easya only

#348 NEW Can edit account on miscellaneous payment (if not transfered)
  htdocs/compta/bank/class/paymentvarious.class.php
  htdocs/compta/bank/various_payment/card.php
  htdocs/core/class/html.form.class.php
Labels: Already merged

#349 FIX invoices order on sells journal
  htdocs/accountancy/journal/sellsjournal.php
Labels: Already merged

#350 FIX width on select list for auxaccount
  htdocs/core/class/html.formaccounting.class.php
Labels: check merged

#351 Accountancy - Fix transfert in accountancy for situation invoice (MT + cents gaps)
  htdocs/accountancy/journal/sellsjournal.php
Labels: easya only
