Repository Easya-Solutions/dolibarr, pull requests merged in 2023-09, with the labels that each got.

#491 2022.5.3 fix opensurvey ajoutdates
  htdocs/opensurvey/wizard/choix_date.php
Labels: Report Easya 2024

#495 5.3 fix stripe language
  htdocs/public/payment/newpayment.php
Labels: check merged

#513 2022.5.3 fix many payments on contractline
  htdocs/compta/facture/class/facture.class.php
  htdocs/langs/de_DE/contracts.lang
  htdocs/langs/en_US/contracts.lang
  htdocs/langs/fr_FR/contracts.lang
  htdocs/public/payment/newpayment.php
Labels: check merged

#519 FIX group by in count elements on invoice list
  htdocs/compta/facture/list.php
Labels: easya only, check merged

#516 NEW : Hex to hsl color conversion function
  htdocs/core/lib/functions2.lib.php
Labels: easya only, Todo
