Repository Easya-Solutions/dolibarr, pull requests merged in 2023-12, with the labels that each got.

#600 NEW lazy load to substitute project variables
  htdocs/core/lib/functions.lib.php
  htdocs/projet/class/project.class.php
Labels: easya 2024

#358 CORE movement stock: Fix compare on float when test on stock dont allow negative transfert
  htdocs/product/class/product.class.php
Labels: check merged, to repost

#612 CORE movement stock: Fix compare on float when test on stock dont allow negative transfert
  htdocs/product/class/product.class.php
Labels: check merged, easya 2024

#619 CORE expedition: Sort batch by dates when create a shipping (independently of the warehouse)
  htdocs/expedition/card.php
Labels: check merged, to repost, easya 2024

#653 Fix sort, add first to be default warehouse first and sort by batch finally
  htdocs/expedition/card.php
Labels: Report Easya 2024
