Repository Easya-Solutions/dolibarr, pull requests merged in 2024-02, with the labels that each got.

#727 FIX Accountancy - Closure
  htdocs/core/menus/init_menu_auguria.sql
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/langs/fr_FR/accountancy.lang
Labels: Already merged, easya 2024

#726 NEW Accountancy - Show accounting result on balance
  htdocs/accountancy/bookkeeping/balance.php
  htdocs/accountancy/class/bookkeeping.class.php
Labels: Already merged, easya 2024

#724 QUAL French term
  htdocs/langs/fr_CA/admin.lang
  htdocs/langs/fr_CA/propal.lang
  htdocs/langs/fr_FR/accountancy.lang
  htdocs/langs/fr_FR/admin.lang
  htdocs/langs/fr_FR/contracts.lang
  htdocs/langs/fr_FR/main.lang
  htdocs/langs/fr_FR/mrp.lang
  htdocs/langs/fr_FR/orders.lang
  htdocs/langs/fr_FR/projects.lang
  htdocs/langs/fr_FR/propal.lang
  htdocs/langs/fr_FR/stocks.lang
  htdocs/langs/fr_FR/supplier_proposal.lang
Labels: easya 2024

#721 FIX SQL migration
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
Labels: Already merged, easya 2024

#720 Fix migration SQL
  htdocs/accountancy/bookkeeping/export.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
Labels: Already merged

#748 Fix : modules templates were not fetched for linkedobjectblock
  htdocs/core/class/html.form.class.php
Labels: check merged

#747 Reception dispatch : copy previous entrepot
  htdocs/fourn/js/lib_dispatch.js.php
Labels: Already merged

#746 New: allow to display account address in pdf sepa mandate. Fix: use -…
  htdocs/core/modules/bank/doc/pdf_sepamandate.modules.php
Labels: Already merged

#736 NEW determine multi-currency price on object line create tpl
  htdocs/core/class/html.form.class.php
  htdocs/core/lib/ajax.lib.php
  htdocs/core/tpl/objectline_create.tpl.php
Labels: check merged

#722 quick edit opportunity status
  htdocs/core/class/html.formprojet.class.php
  htdocs/projet/card.php
Labels: Already merged

#723 2024 rc new quick edit opportunity status
  htdocs/core/class/html.formprojet.class.php
  htdocs/projet/card.php
Labels: Already merged

#671 NEW Supplier Invoice - List - Add choice on ECC country
  htdocs/fourn/facture/list.php
Labels: postponed-dlb, Already merged

#238 2022.5.3 new use account address in sepa mandate
  htdocs/core/modules/bank/doc/pdf_sepamandate.modules.php
Labels: Already merged

#758 FIX|Fix merge tiers type when two tiers are merged
  htdocs/societe/card.php
Labels: check merged

#763 NEW: Add global STOCK_MOVEMENT_FORCE_DO_NOT_CLEAN_EMPTY_LINES to fore do not clean empty lines on movement stock
  htdocs/product/stock/class/mouvementstock.class.php
Labels: check merged

#762 NEW: Add global STOCK_MOVEMENT_FORCE_DO_NOT_CLEAN_EMPTY_LINES to fore do not clean empty lines on movement stock
  htdocs/product/stock/class/mouvementstock.class.php
Labels: check merged
