Repository Easya-Solutions/dolibarr, pull requests merged in 2024-04, with the labels that each got.

#865 CORE ODT: Support des balise [IF] autre par que le corps du document ODT, exemple les entêtes PR #29357
  htdocs/includes/odtphp/odf.php
Labels: easya only, check merged

#864 CORE ODT: Support des balise [IF] autre par que le corps du document ODT, exemple les entêtes PR #29357
  htdocs/includes/odtphp/odf.php
Labels: easya only, check merged

#855 NEW selectionner les lignes pour un virement bancaire
  htdocs/compta/facture/list.php
  htdocs/compta/facture/prelevement.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/create.php
  htdocs/langs/en_US/withdrawals.lang
  htdocs/langs/fr_FR/withdrawals.lang
Labels: easya only

#880 CORE odt: Ajout de la globale EASYA_DISABLE_PDF_AUTO_DOWNLOAD_AFTER_CONVERTION_FROM_ODT
  htdocs/includes/odtphp/odf.php
Labels: easya only, easya 2024

#873 TEMP FIX allow long formconfirms
  htdocs/core/class/html.form.class.php
Labels: easya only, easya 2024
