Repository Easya-Solutions/dolibarr, pull requests merged in 2024-08, with the labels that each got.

#1024 Fix SEPA for supplier invoices
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/create.php
  htdocs/core/class/commoninvoice.class.php
Labels: easya only

#1022 FIX attachment sent by mail from back office of ticket
  htdocs/ticket/class/ticket.class.php
Labels: check merged

#1021 Backport Fix: content-type haeder missing for webhook (#29588)
  htdocs/core/triggers/interface_95_modWebhook_WebhookTriggers.class.php
Labels: Already merged

#1020 Fix error due to missmatch type for duration value
  htdocs/product/class/product.class.php
Labels: check merged

#1033 CORE : FIX avoid from re-initializing result on nested hook getEntity for also resArray
  htdocs/core/class/hookmanager.class.php
Labels: check merged

#1018 NEW_add_last_stock_movement_and_product_nature_to_StocksWithBatch_export
  htdocs/core/modules/modStock.class.php
  htdocs/exports/export.php
  htdocs/product/stock/class/mouvementstock.class.php
Labels: Already merged

#1019 NEW_add_last_stock_movement_and_product_nature_to_StocksWithBatch_export
  htdocs/core/modules/modStock.class.php
  htdocs/exports/export.php
  htdocs/product/stock/class/mouvementstock.class.php
Labels: Already merged

#1038 Backport NEW Add webhook targets REST API
  htdocs/webhook/class/api_webhook.class.php
Labels: Already merged
