Repository Easya-Solutions/dolibarr, pull requests merged in 2024-01, with the labels that each got.

#689 fix: search product by ref in global search result with Unknown column 'pfp.ref_fourn' in 'where clause', already fix in Dolibarr #27071
  htdocs/compta/facture/card.php
  htdocs/product/list.php
Labels: bug, Already merged

#690 Better fix for vatrate by default on credit note
  htdocs/compta/facture/card.php
Labels: easya only

#686 Missing fk_docdet in accountancy
  htdocs/accountancy/journal/purchasesjournal.php
  htdocs/accountancy/journal/sellsjournal.php
Labels: easya only

#710 FIX avoid from re-initializing result on nested hook getEntity
  htdocs/core/lib/functions.lib.php
Labels: check merged

#709 NEW rename const on third-party card
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
Labels: to repost, Todo
