Repository Easya-Solutions/dolibarr, pull requests merged in 2024-03, with the labels that each got.

#801 FIX addline on an order. Wrong computation of pu_ttc.
  htdocs/commande/card.php
Labels: check merged

#811 fix_warehouse_not_showed_onexpedition_lines
  htdocs/expedition/card.php
  htdocs/expedition/class/expedition.class.php
Labels: easya only

#810 fix condition to show warehouse if product is stockable in expedition…
  htdocs/expedition/card.php
  htdocs/expedition/class/expedition.class.php
Labels: easya only

#561 CORE expedition: Fix création d’expédition lorsque que l'on as des entrepôts sans stocks mais que l'on autorise les mouvements de stock négatif
  htdocs/expedition/card.php
Labels: Todo, easya 2024

#821 CORE commande: Fix Move the trigger for delete order line before the SQL request
  htdocs/commande/class/commande.class.php
Labels: check merged

#824 CORE ODT invoice: Fix invoice ODT directory when multientities PR #28991
  htdocs/core/modules/facture/doc/doc_generic_invoice_odt.modules.php
Labels: check merged

#839 set const EASYA VERSION step 5 installation and display Easya version
  htdocs/VERSION
  htdocs/admin/system/dolibarr.php
  htdocs/install/step5.php
  htdocs/main.inc.php
Labels: easya only, easya 2024

#838 NEW Report accounting export with source file on Quadra / FEC model export
  htdocs/accountancy/bookkeeping/export.php
  htdocs/accountancy/class/accountancyexport.class.php
Labels: Already merged

#837 FIX Accountancy export with file or not
  htdocs/accountancy/class/accountancyexport.class.php
Labels: Already merged

#829 NEW Move right from advance to normal for thirdparty information payment page
  htdocs/core/modules/modSociete.class.php
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
  htdocs/societe/paymentmodes.php
Labels: easya only, check merged

#834 NEW Constant to select if typent helps define whether the thirdparty is a company
  htdocs/societe/class/societe.class.php
Labels: check merged
