Repository Easya-Solutions/dolibarr, pull requests merged in 2025-01, with the labels that each got.

#1309 NEW add option to not prefill qty line at shipment creation
  htdocs/admin/expedition.php
  htdocs/expedition/card.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
Labels: check merged

#1294 FIX wrong bank account for payment
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/factures.php
Labels: easya only, Todo

#1267 NEW : ODT {object_type_label} for Invoices and Supplier Invoices
  htdocs/core/class/commondocgenerator.class.php
Labels: postponed-dlb

#1326 CORE expedition: Fix compatibilité PHP8 sur une partie de code spécifique easya dans la creation d'une expedition avec des lots
  htdocs/expedition/card.php
Labels: check merged, easya 2024

#1337 fix facturerec
  htdocs/core/lib/functions.lib.php
Labels: Todo

#1333 Fix default checkbox extrafields
  htdocs/core/class/commonobject.class.php
Labels: Already merged

#1325 CORE expedition: Fix compatibilité PHP8 sur une partie de code spécifique easya dans la creation d'une expedition avec des lots
  htdocs/expedition/card.php
Labels: check merged, easya 2024
