Repository Easya-Solutions/dolibarr, pull requests merged in 2025-03, with the labels that each got.

#1397 2024 rc backport repair utf8mb4
  htdocs/install/repair.php
Labels: easya only

#1271 NEW : 4 Tags for shipment on ODT
  htdocs/core/class/commondocgenerator.class.php
Labels: Already merged

#1418 CORE accountancy account: Backport du plan comptable 2025 (v22)
  htdocs/install/mysql/data/llx_accounting_account_fr.sql
Labels: Todo
